openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /user/{userId}:
    get:
      summary: Get user information
      description: Retrieve information about a specific user.
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user to retrieve information for.
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                userId: 123
                username: john_doe
                email: john.doe@example.com
        '404':
          description: User not found
          content:
            application/json:
              example:
                error: User not found
