openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /accounts/{accountsId}:
    get:
      summary: Get account information
      description: Retrieve the account of a specific user.
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user to retrieve information for.
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                accountid: 12345678
