openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
paths:
  /tasks:
    get:
      summary: Get all tasks
      description: Retrieve a list of all tasks.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                tasks:
                  - id: 1
                    title: Task 1
                    description: Description for Task 1
                  - id: 2
                    title: Task 2
                    description: Description for Task 2

    post:
      summary: Create a new task
      description: Create a new task with the provided details.
      requestBody:
        required: true
        content:
          application/json:
            example:
              title: New Task
              description: Description for the new task
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              example:
                id: 3
                title: New Task
                description: Description for the new task

  /tasks/{taskId}:
    get:
      summary: Get a specific task
      description: Retrieve details for a specific task.
      parameters:
        - name: taskId
          in: path
          required: true
          description: ID of the task to retrieve details for.
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: 1
                title: Task 1
                description: Description for Task 1
        '404':
          description: Task not found
          content:
            application/json:
              example:
                error: Task not found

    put:
      summary: Update a task
      description: Update the details of a specific task.
      parameters:
        - name: taskId
          in: path
          required: true
          description: ID of the task to update.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            example:
              title: Updated Task
              description: Updated description for the task
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              example:
                id: 1
                title: Updated Task
                description: Updated description for the task

    delete:
      summary: Delete a task
      description: Delete a specific task.
      parameters:
        - name: taskId
          in: path
          required: true
          description: ID of the task to delete.
          schema:
            type: integer
      responses:
        '204':
          description: Task deleted successfully
